# Generated by Django 5.0.6 on 2024-08-20 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('courseCode', models.CharField(blank=True, max_length=20, unique=True)),
                ('courseName', models.CharField(max_length=100)),
                ('courseDescription', models.TextField()),
                ('courseVideo', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('courseFile', models.FileField(blank=True, null=True, upload_to='files/')),
                ('number_of_hours', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
